In [2]:
from scipy import stats
import pandas as pd
import numpy as np

 problem statement :
  
 assuming the sample is representative of the population, construct a 99% confidence interval for the mean number of characters printed before the print-head fails using the sample standard deviation. Explain the steps you take and the rationale behind using the t-distribution for this task.

Build 99% Confidence Interval Using Sample Standard Deviation

In [3]:
# create array of data
df=np.array([1.13,1.55,1.43,0.92,1.25,1.36,1.32,0.85,1.07,1.48,1.20,1.33,1.18,1.22,1.29])
df

array([1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.2 ,
       1.33, 1.18, 1.22, 1.29])

In [4]:
df

array([1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.2 ,
       1.33, 1.18, 1.22, 1.29])

In [5]:
n = 15
alpha = 0.01

In [ ]:
# first calculate mean

In [6]:
mean = np.mean(df)
mean

np.float64(1.2386666666666666)

In [ ]:
# second calculate sample standard deviation

In [7]:
standard_deviation =np.std(df)
standard_deviation

np.float64(0.18661427836285438)

In [8]:
t_critical = stats.t.ppf(1-(alpha/2),df = n-1)
t_critical

np.float64(2.976842734370834)

In [9]:
# Use 0.5 to calculate the square root of n for standard error
upper_ci = mean + (t_critical) * (standard_deviation / (n)**0.5)

In [10]:
lower_ci = mean - (t_critical) * (standard_deviation / (n)**0.5)

In [ ]:
print(f"LOWER TO UPPER  OF CONFIDENCE INTERVAL→ [{lower_ci} … {upper_ci}]")

LOWER TO UPPER  OF CONFIDENCE INTERVAL→ [1.095231668626123 … 1.3821016647072102]


b. Build 99% Confidence Interval Using Known Population Standard Deviation
If it were known that the population standard deviation is 0.2 million characters, construct a 99% confidence interval for the mean number of characters printed before failure.   

In [ ]:
"""
 99% confidence interval for the mean durability using a known population standard deviation,
 we will use the Z-distribution, since the population standard deviation (σ) is known.
 """

In [11]:
#known population std
σ= 0.2

In [13]:
df

array([1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.2 ,
       1.33, 1.18, 1.22, 1.29])

In [19]:
mean

np.float64(1.2386666666666666)

In [21]:
sample_mean = np.mean(df)

In [23]:
z_value = stats.norm.ppf(1 - 0.01 / 2)

In [24]:
margin_of_error = z_value * (σ / np.sqrt(n))

In [26]:
ci_lower = sample_mean - margin_of_error
ci_upper = sample_mean + margin_of_error

In [27]:
print(f"Sample Mean: {sample_mean:.3f}")
print(f"Z Critical Value (99%): {z_value:.3f}")
print(f"Margin of Error: {margin_of_error:.3f}")
print(f"99% Confidence Interval: ({ci_lower:.3f}, {ci_upper:.3f})")

Sample Mean: 1.239
Z Critical Value (99%): 2.576
Margin of Error: 0.133
99% Confidence Interval: (1.106, 1.372)
